### ISSUE TITLE
Wrong description of docsify-print

### ISSUE THREAD

**Issue by Pystronic** [anikethsaha/docsify-plugin#11]
Instead of the description for docsify-print, the ReadMe and the print package have the same description as docsify-dark-mode.

From the ReadMe:
> docsify-dark-mode | docsify plugin to add dark mode in your docsify site |
> docsify-print | docsify plugin to add dark mode in your docsify site |  

And in the README of the Package:
> # docsify-print
> This is docsify plugin which enables dark mode for your docsify site

**Comment by anikethsaha** [comment]
Thanks for pointing. Feel free to submit a fix
