### ISSUE TITLE
[changelog] opening the changelog navigates to the root

### ISSUE THREAD

**Issue by tpluscode** [anikethsaha/docsify-plugin#2]
When the changelog is clicked it changes the open page. I think it should be prevented

**Comment by anikethsaha** [comment]
Can you share a Reproducible repo Or the screen shot. 
This is not the default behavior of the plugin. It is not opening any nee pages  
Check the posthtml.org site

**Comment by tpluscode** [comment]
Oh curious, I was not yet live with the changelog and it appears to only happen when running locally...

**Comment by anikethsaha** [comment]
if you can share a repo I can take a look.

**Comment by tpluscode** [comment]
https://github.com/tpluscode/sparql-builder

**Comment by anikethsaha** [comment]
You project looks fine as per config.

**Comment by anikethsaha** [comment]
can you share the screenshots and logs if any

**Comment by tpluscode** [comment]
So, this error happens:

```
index.js:formatted:8 Uncaught TypeError: Cannot read property 'remove' of null
    at window.changelogDisplayHandler (index.js:formatted:8)
    at HTMLAnchorElement.onclick ((index):1)
```

which is in https://github.com/anikethsaha/docsify-plugin/blob/master/packages/docsify-changelog-plugin/src/index.js#L13

**Comment by anikethsaha** [comment]
hey ! it seems it working fine in your site https://t-code.pl/sparql-builder/#/

**Comment by tpluscode** [comment]
Indeed. Only breaks with `docsify serve docs`

**Comment by anikethsaha** [comment]
> Indeed. Only breaks with `docsify serve docs`

Weird ! try with `docsify serve ./docs` !

**Comment by tpluscode** [comment]
No change

**Comment by anikethsaha** [comment]
Let me run that repo locally and check

**Comment by BanditTech** [comment]
I am also having a similar issue. Clicking any of the headings on the changelog will make the active page scroll downwards. [on live](bandittech.github.io/WingmanReloaded)

**Comment by BanditTech** [comment]
I looked at the code, and the link in question is being statically generated on script load. If you replace the static assignment of #/
```
                    t && localStorage.getItem(c) ? l = '<a href="#/" onClick="window.changelogDisplayHandler(); return false;" id="CHANGELOG">CHANGELOG</a>\n                <div id="CHANGELOG_RENDERER">\n                  <div class="CL_content">\n                    <div class="CL_content-body"></div>\n                  </div>\n                </div>' 
                    : (l = '<a href="#/" onClick="window.changelogDisplayHandler(); return false;" id="CHANGELOG"><i id="CHANGELOG_NOTIFY"></i>  CHANGELOG</a>\n                <div id="CHANGELOG_RENDERER">\n                  <div class="CL_content">\n                    <div class="CL_content-body"></div>\n                  </div>\n                </div>', o = c);
```

With the actual address at document.location.href then you would fix this issue.

**Comment by anikethsaha** [comment]
> Also confirming that clicking on the Changelog button will navigate back to the "Homepage"

Yes I faced this as well 👍 

> With the actual address at document.location.href then you would fix this issue.

Yes it will fix. 

Thanks a lot for taking time in investigating the issue. 

PR welcome

**Comment by BanditTech** [comment]
ok, I looked at this some more. We can fix the issue of the page renavigating when you click the changelog button by replacing the href="" with href="javascript:void(0);"

But the issue I am actually finding is that docsify renders the headings as links no matter whether ```# {docsify-ignore-all}``` is present or not. I had found a very clunky temporary solution, wrap the header titles with [](javascript:void(0)) to prevent them from causing the page to move.

is there something I am missing that will prevent docsify from converting the headers into links?

**Comment by anikethsaha** [comment]
> But the issue I am actually finding is that docsify renders the headings as links no matter whether # {docsify-ignore-all} is present or not. I had found a very clunky temporary solution, wrap the header titles with [](javascript:void(0)) to prevent them from causing the page to move.

weirdly its working fine here https://posthtml.org/#/plugins/README

> We can fix the issue of the page renavigating when you click the changelog button by replacing the href="" with href="javascript:void(0);"

Yes this is perfect !

> is there something I am missing that will prevent docsify from converting the headers into links?

I dont think so as docsify ignore should work here !

**Comment by BanditTech** [comment]
I think that all docsify ignore does is not place the contents onto the TOC of the sidebar.

The example you linked to is actually doing exactly what the issue is describing. When you have navigated away  from the homepage, it will go back to the homepage unless you reload the current page (which moves browser.location.href into the window.location.href) and the links are updated

**Comment by BanditTech** [comment]
you can see it occuring every time it goes into a "sidebar" directory, like plugins or getting started section.

Like this is the most common use case scenario:

User visits the webpage, maybe clicks on one of the sidebar items... 

Then they notice there is a changelog notification... they click it... and it brings back to the homepage... Ok not so bad.

They proceeed to scroll down, or navigate away from the page again. OK, now we forgot to close the panel... lets click to close... oops back to homepage :P

**Comment by BanditTech** [comment]
thinking about it, this issue can probably be closed now with that last merge. Since the main issue is the button itself, and that is now resolved. Sorting out the links within the parsed MD is within the realm of the end user, just cannot use headers unless they are manually set to a link. May want to go into more details about that specific case, since its most common to use headers for a changelog.

**Comment by anikethsaha** [comment]
Very well. 
Please comment below to reopen if anyone else think this needs to be fixed (the header issue)
