### ISSUE TITLE
[docsify-dark-mode] Toggle button won't show

### ISSUE THREAD

**Issue by Gaspacchio** [anikethsaha/docsify-plugin#3]
## Problem

I've followed the setup instructions located in [`docsify-plugin/packages/docsify-dark-mode/README.md`](https://github.com/anikethsaha/docsify-plugin/tree/master/packages/docsify-dark-mode) and I couldn't get the toggle to show.

## Solution

I've installed [`docsify-themeable`](https://jhildenbiddle.github.io/docsify-themeable).

## Why this issue?

I've opened this issue to help other people. Furthermore, I would like to submit a PR to improve the docs and I figured that it would be better to have an open issue to reference.

**Comment by anikethsaha** [comment]
it might be of white color. 
Can you inspect the elements and check it. You can override the colors. Just take a look at the options in the docs. 

>  I would like to submit a PR to improve the docs and I figured that it would be better to have an open issue to reference.

That would be great to have more info on the docs. Feel free to investigate and submit the fix 👍

**Comment by Gaspacchio** [comment]
I've just checked the markup and you were right, the button is white (and invisible) by default. I'm currently improving the docs and I'm gonna investigate on improving the default CSS style to show the toggle by default. I'll submit two PR's if this works for you.

![image](https://user-images.githubusercontent.com/43613824/75352463-13514800-58aa-11ea-8d59-004f81acc2cf.png)

**Comment by anikethsaha** [comment]
Yes by default is white, yes updating docs with an appropriate message like the default can be white or something more explanatory would be perfect to add
👍
